server:
  Port 50051

postgres:
  Host: "postgres"
  Port: 5432
  SSL_MODE: "disable"
  DB: "payment"
  User: "postgres"
  Password: "supersecretpassword123"

redis:
  URL: "redis:6379"

forex:
  Key: ""

yoomoney:
  Token: ""
  ClientID: ""
  Receiver:
